```{r}
library(RWeka)
library(partykit)
library(ROCR)
```

**PART 1**

Reading data.

```{r}
sonar = read.csv("sonar.all-data", header=FALSE)

dim(sonar)
str(sonar)
summary(sonar)

head(sonar)
```

**PART 2**

Using C4.5 decision tree.

```{r}
c45_tree_classifier <- J48(V61 ~ ., data = sonar)

c45_tree_classifier
summary(c45_tree_classifier)
table(sonar$V61, predict(c45_tree_classifier))
plot(c45_tree_classifier,
     gp = gpar(fontsize = 6),
     inner_panel=node_inner,
     ip_args=list(abbreviate = TRUE, id = FALSE)
)
```

Experimenting with different parameters.

```{r}
tree_classifier_1 <- J48(V61 ~ ., data = sonar, control = Weka_control(U = TRUE))
tree_classifier_1
summary(tree_classifier_1)

tree_classifier_2 <- J48(V61 ~ ., data = sonar, control = Weka_control(R = TRUE))
tree_classifier_2
summary(tree_classifier_2)

tree_classifier_3 <- J48(V61 ~ ., data = sonar, control = Weka_control(C = 0.1))
tree_classifier_3
summary(tree_classifier_3)

tree_classifier_4 <- J48(V61 ~ ., data = sonar, control = Weka_control(C = 0.5))
tree_classifier_4
summary(tree_classifier_4)

tree_classifier_5 <- J48(V61 ~ ., data = sonar, control = Weka_control(O = TRUE))
tree_classifier_5
summary(tree_classifier_5)

tree_classifier_6 <- J48(V61 ~ ., data = sonar, control = Weka_control(R = TRUE, N = 5))
tree_classifier_6
summary(tree_classifier_6)

tree_classifier_7 <- J48(V61 ~ ., data = sonar, control = Weka_control(R = TRUE, N = 2))
tree_classifier_7
summary(tree_classifier_7)

tree_classifier_8 <- J48(V61 ~ ., data = sonar, control = Weka_control(S = TRUE))
tree_classifier_8
summary(tree_classifier_8)

tree_classifier_9 <- J48(V61 ~ ., data = sonar, control = Weka_control(A = TRUE))
tree_classifier_9
summary(tree_classifier_9)

# Best result
tree_classifier_10 <- J48(V61 ~ ., data = sonar, control = Weka_control(J = TRUE))
tree_classifier_10
summary(tree_classifier_10)

tree_classifier_11 <- J48(V61 ~ ., data = sonar, control = Weka_control(doNotMakeSplitPointActualValue = TRUE))
tree_classifier_11
summary(tree_classifier_11)

tree_classifier_12 <- J48(V61 ~ ., data = sonar, control = Weka_control(J = TRUE, R = TRUE, N = 10))
tree_classifier_12
summary(tree_classifier_12)
```

Calculating classification evaluation measures.

```{r}
findEvalMeasures <- function(predictions, labels) {
  possible_values <- unique(labels)
  size <- length(possible_values)
  
  if (size != 2) {
    return(NULL)
  }
  
  p_symbol <- possible_values[1]
  n_symbol <- possible_values[2]
  p <- length(which(labels == p_symbol))
  n <- length(which(labels == n_symbol))
  tp <- length(which(predictions == p_symbol & labels == p_symbol))
  fp <- length(which(predictions == p_symbol & labels == n_symbol))
  tn <- length(which(predictions == n_symbol & labels == n_symbol))
  fn <- length(which(predictions == n_symbol & labels == p_symbol))
  
  acc <- (tp + tn) / (p + n)
  err <- (fp + fn) / (p + n)
  rec <- tp / p
  prec <- tp / (tp + fp)
  f <- (2 * prec * rec) / (prec + rec)
  
  eval_measures <- list(
    size = size,
    positive_symbol = p_symbol,
    negative_symbol = n_symbol,
    positive = p,
    negative = n,
    true_positive = tp,
    false_positive = fp,
    true_negative = tn,
    false_negative = fn,
    accuracy = acc,
    error = err,
    recall = rec,
    precision = prec,
    f_score = f
  )
  return(eval_measures)
}
```

```{r}
predictions <- as.vector(predict(c45_tree_classifier))
labels <- as.vector(sonar$V61)

eval_measures <- findEvalMeasures(predictions, labels)
eval_measures
```